### ISSUE TITLE
need help, sudden permission denied error ,  It can work a few days ago.

### ISSUE THREAD

**Issue by xiaoyifang** [SonarSource/sonarcloud-github-c-cpp#41]
https://github.com/xiaoyifang/goldendict-ng/actions/runs/5758910580/job/15612139817

`INFO: Final Memory: 48M/167M
ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: java.io.IOException: Cannot run program "/home/runner/work/goldendict-ng/goldendict-ng/.scannerwork/.sonartmp/13901507637514780167/subprocess" (in directory "/home/runner/work/goldendict-ng/goldendict-ng"): error=13, Permission denied
	at com.sonar.cpp.driver.ProcessExecutor.execute(ProcessExecutor.java:73)
	at com.sonar.cpp.driver.ProcessExecutor.execute(ProcessExecutor.java:44)
	at com.sonar.cpp.analyzer.ClangDriver.runCompiler(ClangDriver.java:874)
	at com.sonar.cpp.analyzer.ClangDriver.lambda$probeCompiler$12(ClangDriver.java:944)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
INFO: ------------------------------------------------------------------------
	at com.sonar.cpp.analyzer.ClangDriver.probeCompiler(ClangDriver.java:944)
	at com.sonar.cpp.analyzer.ClangDriver.onCapture(ClangDriver.java:601)
	at com.sonar.cpp.analyzer.CompilerDrivers.onCapture(CompilerDrivers.java:36)
	at com.sonar.cpp.plugin.CFamilySensor.lambda$process$36(CFamilySensor.java:1428)
	at com.sonar.cpp.plugin.BuildWrapperJsonReader.readCaptures(BuildWrapperJsonReader.java:87)`

**Comment by kharus** [comment]
Same issue.
I even re-started old builds which were passing and they failed as well.

**Comment by egorodet** [comment]
Same problem in my project, started reproducing after Sonar Scanner update from v4.8 to v5.0 https://github.com/MethanePowered/MethaneKit/actions/runs/5755106840/job/15612718886

**Comment by ericg138** [comment]
Hello,
Sorry for not getting to this sooner.
We will soon close the GitHub Issues section on this repo. If you still encounter this issue, feel free to open a thread on the [community forum](https://community.sonarsource.com/).
